language: cpp
script: cmake .. && make all && ./SVR_tests
compiler: clang
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    
    - os: osx
      osx_image: xcode9.4

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
