version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install GIT
          command: 'apt-get update && apt-get install -y git'
      - run:
          name: Go to Testing folder
          command: 'cd cpp/testing'
      - run: 
          name: Install Google Tests
          command: 'git clone https://github.com/google/googletest.git'
      - run: 
          name: Install Google Benchmark I
          command: 'git clone https://github.com/google/benchmark.git'
      - run: 
          name: Install Google Benchmark II
          command: 'git clone https://github.com/google/googletest.git benchmark/googletest'
      - run: 
          name: Install Google Benchmark III
          command: 'cd benchmark && mkdir build && cd build && cmake ../ && make'
      - run: 
          name: Build Tests
          command: 'cd cpp && cd testing && cmake .. && make all'
      - run:
          name: SVR Unit Testing
          command: 'cd build && ./SVR_tests'
