version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Installing GIT
          command: 'apt-get update && apt-get install -y git'
      - run: 
          name: Create Build, Binary Files
          command: 'cd cpp/tests && cmake -H. -Bbuild && cmake --build build'
      - run:
          name: SVR Unit Testing
          command: 'cd cpp/tests/bin && ./test_SVR'
      - run:
          name: Run coverage
          command: >
            lcov --directory . --capture --output-file coverage.info &&
            lcov --remove coverage.info '/usr/*' "${HOME}" '/.cache/*' 'cpp/tests/*' --output-file coverage.info &&
            lcov --list coverage.info

      - codecov/upload:
        file: coverage.info
        flags: unittesting
